import { useEffect } from 'react'
import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { ConfigProvider } from 'antd'
import { useAuthStore } from './stores/auth'
import { AccountPage, AdminCategoriesPage, AdminClubsPage, AdminDashboardPage, AdminReviewDetailPage, AdminReviewsPage, AdminUsersPage, AuditLogsPage, ClubDetailPage, ClubEditorPage, ClubListPage, DashboardPage, HomePage, InvitationsPage, LoginPage, PeoplePage, RegistrationStatusPage, RegisterPage, TransfersPage } from './pages'

function AppRoutes() { const hydrate = useAuthStore(s => s.hydrate); const hydrated = useAuthStore(s => s.hydrated); useEffect(() => { void hydrate() }, [hydrate]); if (!hydrated) return null; return <Routes><Route path="/" element={<HomePage />} /><Route path="/clubs" element={<ClubListPage />} /><Route path="/clubs/:slug" element={<ClubDetailPage />} /><Route path="/login" element={<LoginPage />} /><Route path="/register" element={<RegisterPage />} /><Route path="/registration-status" element={<RegistrationStatusPage />} /><Route path="/dashboard" element={<DashboardPage />} /><Route path="/dashboard/clubs" element={<DashboardPage />} /><Route path="/dashboard/clubs/new" element={<ClubEditorPage create />} /><Route path="/dashboard/clubs/:id/edit" element={<ClubEditorPage />} /><Route path="/dashboard/clubs/:id/people" element={<PeoplePage />} /><Route path="/dashboard/invitations" element={<InvitationsPage />} /><Route path="/dashboard/transfers" element={<TransfersPage />} /><Route path="/dashboard/account" element={<AccountPage />} /><Route path="/admin" element={<AdminDashboardPage />} /><Route path="/admin/users" element={<AdminUsersPage />} /><Route path="/admin/club-reviews" element={<AdminReviewsPage />} /><Route path="/admin/club-reviews/:revisionId" element={<AdminReviewDetailPage />} /><Route path="/admin/clubs" element={<AdminClubsPage />} /><Route path="/admin/categories" element={<AdminCategoriesPage />} /><Route path="/admin/audit-logs" element={<AuditLogsPage />} /><Route path="*" element={<HomePage />} /></Routes> }

export default function App() { return <ConfigProvider theme={{ token: { colorPrimary: '#123B63', borderRadius: 8, fontFamily: 'PingFang SC, Microsoft YaHei, Noto Sans SC, sans-serif' } }}><BrowserRouter><AppRoutes /></BrowserRouter></ConfigProvider> }
